name: go vet test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build
        run: go build -v ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
